name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Run tests 🧪
        uses: cypress-io/github-action@v7.4.0
        env:
          DEBUG: local-cypress

      - name: Lint source 🧹
        run: npm run lint

      - name: Lint Cypress specs 🧹
        run: npm run lint:cypress
